---
# Install tuned packages

- name: unwanted packages are removed
  package:
    name: "{{ tuned_packages_remove }}"
    state: absent
  become: true
  when: tuned_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ tuned_packages_repos }}"
    state: "{{ tuned_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ tuned_packages_prereq }}"
    state: "{{ tuned_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ tuned_packages_install }}"
    state: "{{ tuned_packages_state }}"
  become: true
